name: Publish Multi-Architecture Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование кода
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Установка Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Шаг 3: Вход в GitHub Container Registry
      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Шаг 4: Сборка и публикация Docker-образа
      - name: Build and push Docker image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ghcr.io/vladimirvereshchagin/telegram_exporter:latest \
            -t ghcr.io/vladimirvereshchagin/telegram_exporter:${{ github.sha }} \
            --push .